id: I07341014
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 14:52:10.113686
last_modified: 2023-02-09 14:52:10.113799
source_metadata:
  title: 'PP: Vajracchedikā Prajñāpāramitā'
  language: zh
bases:
  2DE0:
    base_file: 2DE0.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
